local ASCT, L = ASCT_Table, ASCT_locale_Table
if ASCT.Client.LE_EXPANSION_LEVEL["isShadowlandsWow"] and ASCT.Client.tocversion["90207"] then
	ASCT.Database.Spells["Spells_SL"] = {
	--Races
	["Race"] = {
		["Blood Elf"] = false,
		Orc = false,
		Undead = false,
		Troll = false,
		Tauren = false,
		Draenei = false,
		Gnome = false,
		Human = false,
		["Night Elf"] = false,
		Dwarf = false,
		Worgen = false,
		Pandaren = false,
		["Void Elf"] = false,
		["Lightforged Draenei"] = false,
		["Dark Iron Dwarf"] = false,
		Mechagnome = false,
		["Kul Tiran"] = false,
		Goblin = false,
		Nightborne = false,
		["Highmountain Tauren"] = false,
		Vulpera = false,
		["Zandalari Troll"] = false,
		["Mag'har Orc"] = false,
		},
	--Classes
	["Class"] = {
		Rogue = false,
		Priest = false,
		Warrior = false,
		Druid = false,
		Warlock = false,
		Shaman = false,
      	Hunter = false,
		Paladin = false,
		Mage = false,
		Death_Knight = false,
		Demon_Hunter = false,
		Monk = false,
		},
	--Rogue spells
	["Assassination"] = {
		["Vendetta"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Garrote"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Kidney Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Crimson Vial"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Outlaw"] = {
		["Adrenaline Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blade Flurry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Roll the Bones"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Between the Eyes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Gouge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Grappling Hook"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ghostly Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blade Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Killing Spree"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shiv"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Evasion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Feint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sprint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Subtlety"] = {
		["Shadow Dance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadow Blades"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Symbols of Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shuriken Tornado"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Secret Technique"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadowstep"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cloak of Shadows"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Vanish"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Stealth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shroud of Concealment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Distract"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Tricks of the Trade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
--Priest spells
	["Shadow"] = {
		["Vampiric Embrace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dispersion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Silence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Void Eruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Void Bolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Psychic Horror"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Purify Disease"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mind Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Surrender to Madness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadow Crash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Damnation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadowfiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Void Torrent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadow Covenant"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadow Word: Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Psychic Scream"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mind Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
    ["Holy_Priest"] = {
		["Symbol of Hope"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Guardian Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shining Force"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Divine Star"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Divine Hymn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Holy Word: Chastise"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Holy Word: Serenity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Prayer of Mending"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Holy Word: Sanctify"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Holy Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Circle of Healing"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Holy Word: Salvation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Apotheosis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Desperate Prayer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Leap of Faith"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
    ["Discipline"] = {
		["Pain Suppression"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Penance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rapture"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Power Word: Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Power Word: Radiance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Schism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mindbender"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Angelic Feather"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Evangelism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Halo"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Purify"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spirit Shell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Power Infusion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mass Dispel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	  --Warrior spells
	["Arms"] = {
		["Colossus Smash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Die by the Sword"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bladestorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mortal Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Overpower"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sweeping Strikes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Defensive Stance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Warbreaker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cleave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Deadly Calm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Skullsplitter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Charge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Execute"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shield Slam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shattering Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ignore Pain"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Fury"] = {
		["Piercing Howl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Impending Victory"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Recklessness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bloodthirst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Enraged Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Raging Blow"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Siegebreaker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Onslaught"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Heroic Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Berserker Rage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Battle Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Intervene"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Protection_Warrior"] = {
		["Avatar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dragon Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Demoralizing Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shockwave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shield Wall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Last Stand"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ravager"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Challenging Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Storm Bolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rallying Cry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Heroic Leap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spell Reflection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Intimidating Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shield Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Taunt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Pummel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
		--Druid Spells
	["Balance"] = {
		["Celestial Alignment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Typhoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Solar Beam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fury of Elune"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Force of Nature"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Incarnation: Chosen of Elune"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["New Moon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Barkskin"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dreamwalk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Feral_Combat"] = {
		["Tiger's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Maim"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Feral Frenzy"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Brutal Slash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Incarnation: King of the Jungle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Remove Corruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Survival Instincts"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soothe"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mangle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Thrash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Prowl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Frenzied Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Incapacitating Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Incarnation: Guardian of Ursoc"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Pulverize"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bristling Fur"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Berserk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Skull Bash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Growl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Stampeding Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Druid_Restoration"] = {
		["Wild Growth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Tranquility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Swiftmend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Nature's Cure"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ironbark"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ursol's Vortex"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Nature's Swiftness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Flourish"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Incarnation: Tree of Life"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Overgrowth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Innervate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rebirth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Charm Woodland Creature"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Warlock spells
	["Affliction"] = {
		["Create Soulwell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Unending Resolve"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soulstone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ritual of Summoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ritual of Doom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Haunt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Grimoire of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dark Soul: Misery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Phantom Singularity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Darkglare"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Vile Taint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
    ["Demonology"] = {
		["Demonic Gateway"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Demonic Circle: Teleport"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fel Domination"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Demonic Circle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Demonic Tyrant"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Call Dreadstalkers"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Power Siphon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Grimoire: Felguard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Vilefiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Demonic Strength"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bilescourge Bombers"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soul Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Destruction"] = {
		["Shadowfury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Conflagrate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Havoc"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Infernal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shadowburn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cataclysm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dark Soul: Instability"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soul Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Channel Demonfire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Shaman spells
	["Elemental"] = {
		["Fire Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Lava Burst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Thunderstorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Storm Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Liquid Magma Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Stormkeeper"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Elemental Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Echoing Shock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ancestral Guidance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Icefury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Static Discharge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hex"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Earth Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Tremor Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Wind Shear"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Flame Shock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Capacitor Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Astral Shift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Earthbind Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Astral Recall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		},
	["Enhancement"] = {
		["Feral Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Lava Lash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Stormstrike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Crash Lightning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spirit Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Feral Lunge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Earthen Spike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sundering"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fire Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ice Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Primal Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Shaman_Restoration"] = {
		["Cleanse Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spiritwalker's Grace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ascendance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Healing Tide Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Riptide"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spirit Link Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Healing Rain"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Purify Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mana Tide Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cloudburst Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Earthen Wall Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Earthgrab Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Wellspring"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Downpour"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Surge of Earth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Healing Stream Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Hunter spells
	["Beast Mastery"] = {
		["Feed Pet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Tar Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Misdirection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Tranquilizing Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Kill Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mend Pet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Kill Command"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bestial Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Intimidation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Counter Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Barbed Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aspect of the Wild"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Concussive Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dire Beast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Chimaera Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["A Murder of Crows"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Stampede"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bloodshed"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Binding Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	  },
   ["Marksmanship"] = {
		["Disengage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Play Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Exhilaration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Wailing Arrow"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aimed Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Trueshot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rapid Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bursting Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Explosive Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Double Tap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Volley"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
   ["Survival"] = {
		["Freezing Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aspect of the Turtle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aspect of the Cheetah"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aspect of the Chameleon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aspect of the Eagle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Feign Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Flare"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Wildfire Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Coordinated Assault"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Carve"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Muzzle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Harpoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Steel Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Chakrams"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Butchery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Flanking Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
	--Paladin
	["Holy_Paladin"] = {
		["Consecration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Lay on Hands"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Contemplation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Turn Evil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Holy Shock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Divine Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Aura Mastery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cleanse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Avenging Crusader"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Beacon of Virtue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bestow Faith"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Light's Hammer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rule of Law"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Protection_Paladin"] = {
		["Blessing of Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Divine Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blessing of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blessing of Freedom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hammer of Justice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hammer of Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hand of Reckoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Divine Steed"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Guardian of Ancient Kings"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ardent Defender"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Avenger's Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hammer of the Righteous"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blessing of Spellwarding"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blessed Hammer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Moment of Glory"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Righteous Defense"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Retribution"] = {
		["Avenging Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Judgment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Crusader Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rebuke"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cleanse Toxins"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Shield of Vengeance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Wake of Ashes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blade of Justice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hand of Hindrance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Crusade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Final Reckoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Eye for an Eye"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Execution Sentence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Mage Spells
	["Arcane"] = {
		["Time Warp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mirror Image"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Illusion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Remove Curse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Counterspell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blink"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Arcane Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Greater Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Arcane Power"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Touch of the Magi"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Evocation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Prismatic Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Presence of Mind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Arcane Familiar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Arcane Orb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Supernova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Shattrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Stonard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Theramore"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Silvermoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Exodar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Stormwind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Ironforge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Darnassus"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Orgrimmar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Undercity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Thunder Bluff"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Oribos"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Dalaran - Northrend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ancient Portal: Dalaran"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Warspear"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Vale of Eternal Blossoms"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Portal: Tol Barad"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Fire"] = {
		["Fire Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Combustion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dragon's Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Alter Time"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blazing Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Phoenix Flames"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Meteor"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Living Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blast Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Frost_Mage"] = {
		["Ice Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Frost Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ice Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Cone of Cold"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Water Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Icy Veins"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blizzard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Frozen Orb"] =  {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Comet Storm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ice Floes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ice Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ray of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Ebonbolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Demon Hunter Spells
	["Havoc"] = {
		["Metamorphosis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blur"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Imprison"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spectral Sight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Immolation Aura"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Disrupt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Torment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Eye Beam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Vengeful Retreat"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Darkness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blade Dance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Netherwalk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Felblade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fel Eruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Glaive Tempest"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fel Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Essence Break"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Vengeance"] = {
		["Consume Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Throw Glaive"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fel Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soul Carver"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Chaos Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fiery Brand"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sigil of Misery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Demon Spikes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fel Devastation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sigil of Silence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Infernal Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sigil of Flame"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fracture"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Sigil of Chains"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soul Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bulk Extraction"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Death_Knight Spells
	["Blood"] = {
		["Sacrificial Pact"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Corpse Exploder"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dark Command"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dancing Rune Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Asphyxiate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blood Boil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Gorefiend's Grasp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rune Tap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Vampiric Blood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blooddrinker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blood Tap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Tombstone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Death Pact"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Bonestorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Consumption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mark of Blood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Frost_DK"] = {
		["Icebound Fortitude"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mind Freeze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Lichborne"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Wraith Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Remorseless Winter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Frostwyrm's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Pillar of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Empower Rune Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Glacial Advance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Breath of Sindragosa"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blinding Sleet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Horn of Winter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Hypothermic Presence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Unholy"] = {
		["Death and Decay"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Anti-Magic Zone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Death Grip"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Anti-Magic Shell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Raise Ally"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Death's Advance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Death Gate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Raise Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Dark Transformation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Army of the Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Apocalypse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Gargoyle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Soul Reaper"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Unholy Blight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Defile"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Unholy Assault"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Monk Spells
	["Brewmaster"] = {
		["Paralysis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Roll"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Leg Sweep"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Blackout Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Touch of Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Zen Meditation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Purifying Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Invoke Niuzao, the Black Ox"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Keg Smash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Celestial Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Breath of Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Clash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Black Ox Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Black Ox Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Exploding Keg"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Mistweaver"] = {
		["Transcendence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Transcendence: Transfer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Expel Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Detox"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Healing Elixir"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Life Cocoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rising Sun Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Essence Font"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Thunder Focus Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Revival"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Summon Jade Serpent Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Invoke Chi-Ji, the Red Crane"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mana Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Refreshing Jade Wind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Song of Chi-Ji"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Windwalker"] = {
		["Fortifying Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Zen Pilgrimage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Provoke"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Touch of Fatality"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rushing Jade Wind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Diffuse Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Spear Hand Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Storm, Earth, and Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Invoke Xuen, the White Tiger"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fists of Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Touch of Karma"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Flying Serpent Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Whirling Dragon Punch"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Fist of the White Tiger"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Serenity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Energizing Elixir"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Racials
	["Blood Elf"] = {
		["Arcane Torrent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Orc"] = {
		["Blood Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Undead"] = {
		["Cannibalize"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Will of the Forsaken"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Troll"] = {
		["Berserking"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Tauren"] = {
		["War Stomp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Draenei"] = {
		["Gift of the Naaru"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Gnome"] = {
		["Escape Artist"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Human"] = {
		["Will to Survive"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Night Elf"] = {
		["Shadowmeld"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Dwarf"] = {
		["Stoneform"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Worgen"] = {
		["Darkflight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Pandaren"] = {
		["Quaking Palm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Void Elf"] = {
		["Spatial Rift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Lightforged Draenei"] = {
		["Forge of Light"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Light's Judgment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Dark Iron Dwarf"] = {
		["Fireblood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mole Machine"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Mechagnome"] = {
		["Hyper Organic Light Originator"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Kul Tiran"] = {
		["Haymaker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Goblin"] = {
		["Rocket Jump"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rocket Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Pack Hobgoblin"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Nightborne"] = {
		["Cantrips"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Arcane Pulse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Highmountain Tauren"] = {
		["Bull Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Vulpera"] = {
		["Bag of Tricks"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Make Camp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Rummage Your Bag"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Return to Camp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Zandalari Troll"] = {
		["Embrace of the Loa"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Pterrordax Swoop"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Regeneratin'"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Mag'har Orc"] = {
		["Ancestral Call"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
}
local Lust_Table
if select(3, ASCT.API.Documentation["UnitClass"]("player")) == 7 and select(2, ASCT.API.Documentation["UnitFactionGroup"]("player")) == L["Alliance"] then
Lust_Table = {["Heroism"] = {SpellEnable = false, iconEnable = false, nameEnable = false}}
ASCT.Functions.Table["TableCombine"](ASCT.Database.Spells["Spells_SL"]["Enhancement"], Lust_Table)
elseif select(3, ASCT.API.Documentation["UnitClass"]("player")) == 7 and select(2, ASCT.API.Documentation["UnitFactionGroup"]("player")) == L["Horde"] then
Lust_Table = { ["Bloodlust"] = {SpellEnable = false, iconEnable = false, nameEnable = false} }
ASCT.Functions.Table["TableCombine"](ASCT.Database.Spells["Spells_SL"]["Enhancement"], Lust_Table)
end
end