local ASCT = ASCT_Table
--ASCT.Strings.EventName
ASCT.Strings.EventName["CHAT_MSG_SYSTEM"] = "CHAT_MSG_SYSTEM"
ASCT.Strings.EventName["CHAT_MSG_LOOT"] = "CHAT_MSG_LOOT"
ASCT.Strings.EventName["CHAT_MSG_MONEY"] = "CHAT_MSG_MONEY"
ASCT.Strings.EventName["CHAT_MSG_CURRENCY"] = "CHAT_MSG_CURRENCY"
ASCT.Strings.EventName["CHAT_MSG_COMBAT_HONOR_GAIN"] = "CHAT_MSG_COMBAT_HONOR_GAIN"
ASCT.Strings.EventName["CHAT_MSG_COMBAT_XP_GAIN"] = "CHAT_MSG_COMBAT_XP_GAIN"
ASCT.Strings.EventName["CHAT_MSG_SKILL"] = "CHAT_MSG_SKILL"
ASCT.Strings.EventName["CHAT_MSG_COMBAT_FACTION_CHANGE"] = "CHAT_MSG_COMBAT_FACTION_CHANGE"