local ASCT = ASCT_Table
--ASCT.Strings.EventName
ASCT.Strings.EventName["COMBAT_RATING_UPDATE"] = "COMBAT_RATING_UPDATE"
ASCT.Strings.EventName["COMBAT_LOG_EVENT"] = "COMBAT_LOG_EVENT"
ASCT.Strings.EventName["COMBAT_LOG_EVENT_UNFILTERED"] = "COMBAT_LOG_EVENT_UNFILTERED"