local ASCT = ASCT_Table
--ASCT.Strings.EventName
ASCT.Strings.EventName["TRANSMOG_COLLECTION_SOURCE_ADDED"] = "TRANSMOG_COLLECTION_SOURCE_ADDED"
ASCT.Strings.EventName["TRANSMOG_COLLECTION_SOURCE_REMOVED"] = "TRANSMOG_COLLECTION_SOURCE_REMOVED"
ASCT.Strings.EventName["TRANSMOG_COLLECTION_UPDATED"] = "TRANSMOG_COLLECTION_UPDATED"
ASCT.Strings.EventName["TRANSMOG_COSMETIC_COLLECTION_SOURCE_ADDED"] = "TRANSMOG_COSMETIC_COLLECTION_SOURCE_ADDED"