local ASCT = ASCT_Table
--ASCT.Strings.EventName
ASCT.Strings.EventName["UNIT_AURA"] = "UNIT_AURA"
ASCT.Strings.EventName["UNIT_SPELLCAST_SUCCEEDED"] = "UNIT_SPELLCAST_SUCCEEDED"
ASCT.Strings.EventName["UNIT_STATS"] = "UNIT_STATS"
ASCT.Strings.EventName["UNIT_POWER_FREQUENT"] = "UNIT_POWER_FREQUENT"
ASCT.Strings.EventName["UNIT_ATTACK_POWER"] = "UNIT_ATTACK_POWER"
ASCT.Strings.EventName["UNIT_RESISTANCES"] = "UNIT_RESISTANCES"
ASCT.Strings.EventName["UNIT_MAXHEALTH"] = "UNIT_MAXHEALTH"
ASCT.Strings.EventName["UNIT_QUEST_LOG_CHANGED"] = "UNIT_QUEST_LOG_CHANGED"