local ASCT = ASCT_Table
---------------------------
--ASCT.Strings.CR
---------------------------
ASCT.Strings.CR["CR_WEAPON_SKILL"] = CR_WEAPON_SKILL; --1
ASCT.Strings.CR["CR_DEFENSE_SKILL"] = CR_DEFENSE_SKILL; --2
ASCT.Strings.CR["CR_DODGE"] = CR_DODGE; --3
ASCT.Strings.CR["CR_PARRY"] = CR_PARRY; --4
ASCT.Strings.CR["CR_BLOCK"] = CR_BLOCK; --5
ASCT.Strings.CR["CR_HIT_MELEE"] = CR_HIT_MELEE; --6
ASCT.Strings.CR["CR_HIT_RANGED"] = CR_HIT_RANGED; --7
ASCT.Strings.CR["CR_HIT_SPELL"] = CR_HIT_SPELL; --8
ASCT.Strings.CR["CR_CRIT_MELEE"] = CR_CRIT_MELEE; --9
ASCT.Strings.CR["CR_CRIT_RANGED"] = CR_CRIT_RANGED; --10
ASCT.Strings.CR["CR_CRIT_SPELL"]  = CR_CRIT_SPELL; --11
ASCT.Strings.CR["CR_MULTISTRIKE"]  = CR_MULTISTRIKE; --12
ASCT.Strings.CR["CR_READINESS"] = CR_READINESS; --13
ASCT.Strings.CR["CR_SPEED"] = CR_SPEED; --14
ASCT.Strings.CR["CR_RESILIENCE_CRIT_TAKEN"] = CR_RESILIENCE_CRIT_TAKEN; --15
ASCT.Strings.CR["CR_RESILIENCE_PLAYER_DAMAGE_TAKEN"] = CR_RESILIENCE_PLAYER_DAMAGE_TAKEN; --16
ASCT.Strings.CR["CR_LIFESTEAL"] = CR_LIFESTEAL; --17
ASCT.Strings.CR["CR_HASTE_MELEE"] = CR_HASTE_MELEE; --18
ASCT.Strings.CR["CR_HASTE_RANGED"] = CR_HASTE_RANGED; --19
ASCT.Strings.CR["CR_HASTE_SPELL"] = CR_HASTE_SPELL; --20
ASCT.Strings.CR["CR_AVOIDANCE"] = CR_AVOIDANCE; --21
ASCT.Strings.CR["CR_WEAPON_SKILL_OFFHAND"] = CR_WEAPON_SKILL_OFFHAND; --22
ASCT.Strings.CR["CR_WEAPON_SKILL_RANGED"] = CR_WEAPON_SKILL_RANGED; --23
ASCT.Strings.CR["CR_EXPERTISE"] = CR_EXPERTISE; --24
ASCT.Strings.CR["CR_ARMOR_PENETRATION"] = CR_ARMOR_PENETRATION; --25
ASCT.Strings.CR["CR_MASTERY"] = CR_MASTERY; --26
ASCT.Strings.CR["CR_PVP_POWER"] = CR_PVP_POWER; --27
--ASCT.Strings.CR[""] = CR_ --28
ASCT.Strings.CR["CR_VERSATILITY_DAMAGE_DONE"] = CR_VERSATILITY_DAMAGE_DONE; --29
--ASCT.Strings.CR[""] = CR_ --30
ASCT.Strings.CR["CR_VERSATILITY_DAMAGE_TAKEN"] = CR_VERSATILITY_DAMAGE_TAKEN; --31