local ASCT = ASCT_Table
--ASCT.Str_Int.Class
ASCT.Str_Int.Class["Warrior"] = 1; -- (Warrior)
ASCT.Str_Int.Class["Paladin"] = 2; -- (Paladin)
ASCT.Str_Int.Class["Hunter"] = 3; -- (Hunter)
ASCT.Str_Int.Class["Rogue"] = 4; -- (Rogue)
ASCT.Str_Int.Class["Priest"] = 5;  -- (Priest)
ASCT.Str_Int.Class["Death Knight"] = 6; -- (Death Knight)
ASCT.Str_Int.Class["Shaman"] = 7; -- (Shaman)
ASCT.Str_Int.Class["Mage"] = 8; -- (Mage)
ASCT.Str_Int.Class["Warlock"] = 9; -- (Warlock)
ASCT.Str_Int.Class["Monk"] = 10; -- (Monk)
ASCT.Str_Int.Class["Druid"] = 11; -- (Druid)
ASCT.Str_Int.Class["Demon Hunter"] = 12; -- (Demon Hunter)
ASCT.Str_Int.Class["Evoker"] = 13; -- (Evoker)