local ASCT = ASCT_Table
---------------------------
--ASCT.Str_Int.CR
---------------------------
ASCT.Str_Int.CR["CR_WEAPON_SKILL"] = 1;
ASCT.Str_Int.CR["CR_DEFENSE_SKILL"] = 2;
ASCT.Str_Int.CR["CR_DODGE"] = 3;
ASCT.Str_Int.CR["CR_PARRY"] = 4;
ASCT.Str_Int.CR["CR_BLOCK"] = 5;
ASCT.Str_Int.CR["CR_HIT_MELEE"] = 6;
ASCT.Str_Int.CR["CR_HIT_RANGED"] = 7;
ASCT.Str_Int.CR["CR_HIT_SPELL"] = 8;
ASCT.Str_Int.CR["CR_CRIT_MELEE"] = 9;
ASCT.Str_Int.CR["CR_CRIT_RANGED"] = 10;
ASCT.Str_Int.CR["CR_CRIT_SPELL"]  = 11;
ASCT.Str_Int.CR["CR_MULTISTRIKE"]  = 12;
ASCT.Str_Int.CR["CR_READINESS"] = 13;
ASCT.Str_Int.CR["CR_SPEED"] = 14;
ASCT.Str_Int.CR["CR_RESILIENCE_CRIT_TAKEN"] = 15;
ASCT.Str_Int.CR["CR_RESILIENCE_PLAYER_DAMAGE_TAKEN"] = 16;
ASCT.Str_Int.CR["CR_LIFESTEAL"] = 17;
ASCT.Str_Int.CR["CR_HASTE_MELEE"] = 18;
ASCT.Str_Int.CR["CR_HASTE_RANGED"] = 19;
ASCT.Str_Int.CR["CR_HASTE_SPELL"] = 20;
ASCT.Str_Int.CR["CR_AVOIDANCE"] = 21;
ASCT.Str_Int.CR["CR_WEAPON_SKILL_OFFHAND"] = 22;
ASCT.Str_Int.CR["CR_WEAPON_SKILL_RANGED"] = 23;
ASCT.Str_Int.CR["CR_EXPERTISE"] = 24;
ASCT.Str_Int.CR["CR_ARMOR_PENETRATION"] = 25;
ASCT.Str_Int.CR["CR_MASTERY"] = 26;
ASCT.Str_Int.CR["CR_PVP_POWER"] = 27;
--ASCT.Str_Int.CR[""] = CR_ --28
ASCT.Str_Int.CR["CR_VERSATILITY_DAMAGE_DONE"] = 29;
--ASCT.Str_Int.CR[""] = CR_ --30
ASCT.Str_Int.CR["CR_VERSATILITY_DAMAGE_TAKEN"] = 31;