local ASCT = ASCT_Table
---------------------------
--ASCT.Str_Int.CR
---------------------------
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_CLASSIC"] = 0
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_BURNING_CRUSADE"] = 1
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_WRATH_OF_THE_LICH_KING"] = 2
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_CATACLYSM"] = 3
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_MISTS_OF_PANDARIA"] = 4
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_WARLORDS_OF_DRAENOR"] = 5
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_LEGION"] = 6
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_BATTLE_FOR_AZEROTH"] = 7
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_SHADOWLANDS"] = 8
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_DRAGONFLIGHT"] = 9
ASCT.Str_Int.LE_EXPANSION_LEVEL["LE_EXPANSION_11_0"] = 10