local ASCT = ASCT_Table
--LE_EXPANSION_LEVEL_Current_or_Pervious
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_LEVEL_CURRENT"] = LE_EXPANSION_LEVEL_CURRENT
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_LEVEL_PREVIOUS"] = LE_EXPANSION_LEVEL_PREVIOUS
--LE_EXPANSION_LEVEL_Expansion
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_CLASSIC"] = LE_EXPANSION_CLASSIC
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_BURNING_CRUSADE"] = LE_EXPANSION_BURNING_CRUSADE
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_WRATH_OF_THE_LICH_KING"] = LE_EXPANSION_WRATH_OF_THE_LICH_KING
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_CATACLYSM"] = LE_EXPANSION_CATACLYSM
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_MISTS_OF_PANDARIA"] = LE_EXPANSION_MISTS_OF_PANDARIA
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_WARLORDS_OF_DRAENOR"] = LE_EXPANSION_WARLORDS_OF_DRAENOR
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_LEGION"] = LE_EXPANSION_LEGION
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_BATTLE_FOR_AZEROTH"] = LE_EXPANSION_BATTLE_FOR_AZEROTH
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_SHADOWLANDS"] = LE_EXPANSION_SHADOWLANDS
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_DRAGONFLIGHT"] = LE_EXPANSION_DRAGONFLIGHT