local ASCT = ASCT_Table
--LE_EXPANSION_LEVEL_Current_or_Pervious
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_LEVEL_CURRENT"] = LE_EXPANSION_LEVEL_CURRENT
ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_LEVEL_PREVIOUS"] = LE_EXPANSION_LEVEL_PREVIOUS