local ASCT = ASCT_Table
local Keys = ASCT.Keys
local Client = Keys.Metatables["Client"]
---------------------------
--LE_EXPANSION_LEVEL_CURRENT
---------------------------
-- Value = 0
Client.LE_EXPANSION_LEVEL["isVanillaWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_CLASSIC"])
-- Value = 1
Client.LE_EXPANSION_LEVEL["isTbcWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_BURNING_CRUSADE"])
-- Value = 2
Client.LE_EXPANSION_LEVEL["isWrathWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_WRATH_OF_THE_LICH_KING"])
-- Value = 3
Client.LE_EXPANSION_LEVEL["isCataclysmWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_CATACLYSM"])
-- Value = 4
Client.LE_EXPANSION_LEVEL["isMOPWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_MISTS_OF_PANDARIA"])
-- Value = 5
Client.LE_EXPANSION_LEVEL["isWarlordsWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_WARLORDS_OF_DRAENOR"])
-- Value = 6
Client.LE_EXPANSION_LEVEL["isLegionWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_LEGION"])
-- Value = 7
Client.LE_EXPANSION_LEVEL["isBFAWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_BATTLE_FOR_AZEROTH"])
-- Value = 8
Client.LE_EXPANSION_LEVEL["isShadowlandsWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_SHADOWLANDS"])
-- Value = 9
Client.LE_EXPANSION_LEVEL["isDragonFlightWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_DRAGONFLIGHT"])
-- Value = 10
Client.LE_EXPANSION_LEVEL["isTheWarWithinWow"] = ASCT.API.Documentation["LE_EXPANSION_LEVEL_CURRENT_Equal"](ASCT.Strings.LE_EXPANSION_LEVEL["LE_EXPANSION_WAR_WITHIN"])