local ASCT, L = ASCT_Table, ASCT_locale_Table
if ASCT.Client.LE_EXPANSION_LEVEL["isMOPWow"] and ASCT.Client.tocversion["is50500"] then
    ASCT.Database.Spells["Spells_MOP"] = {
    ------------------------
    --Races
    ------------------------
        ["Race"] = {
            ["Blood Elf"] = false,
            ["Draenei"] = false,
            ["Dwarf"] = false,
            ["Gnome"] = false,
            ["Goblin"] = false,
            ["Human"] = false,
            ["Night Elf"] = false,
            ["Orc"] = false,
            ["Pandaren"] = false,
            ["Tauren"] = false,
            ["Troll"] = false,
            ["Undead"] = false,
            ["Worgen"] = false,
            },
    ------------------------
    --Classes
    ------------------------
        ["Class"] = {
            ["Death Knight"] = false,
            ["Druid"] = false,
            ["Hunter"] = false,
            ["Mage"] = false,
            ["Monk"] = false,
            ["Paladin"] = false,
            ["Priest"] = false,
            ["Rogue"] = false,
            ["Shaman"] = false,
            ["Warlock"] = false,
            ["Warrior"] = false,
            },
    ------------------------
    --Rogue spells
    ------------------------
        ["Assassination"] = {
            ["Kidney Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Marked for Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Vendetta"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Combat"] = {
            ["Adrenaline Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Blade Flurry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Combat Readiness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dismantle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Evasion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Gouge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Killing Spree"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Redirect"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Sprint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Subtlety"] = {
            ["Blind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Cloak of Shadows"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Distract"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Premeditation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Preparation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadow Blades"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadow Dance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadow Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadowstep"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shroud of Concealment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Smoke Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stealth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Tricks of the Trade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Vanish"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Priest spells
    ------------------------
        ["Shadow"] = {
            ["Dispersion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mass Dispel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mind Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mindbender"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Psychic Horror"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Psychic Scream"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Psyfiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadow Word: Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadowfiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Silence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spectral Guise"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spirit Shell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Vampiric Embrace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Void Shift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Void Tendrils"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
          },
       ["Holy_Priest"] = {
            ["Angelic Feather"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Cascade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chakra: Chastise"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chakra: Sanctuary"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chakra: Serenity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Circle of Healing"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Desperate Prayer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Divine Hymn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Guardian Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Halo"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Holy Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hymn of Hope"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Leap of Faith"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lightwell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Prayer of Mending"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Purify"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
       ["Discipline"] = {
            ["Archangel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Divine Star"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fear Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Inner Focus"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Pain Suppression"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Penance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Power Infusion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Power Word: Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Power Word: Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Power Word: Solace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
          },
    ------------------------
    --Warrior spells
    ------------------------
        ["Arms"] = {
            ["Battle Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Berserker Rage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Bladestorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Bloodbath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Charge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Commanding Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Demoralizing Banner"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Disrupting Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dragon Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hamstring"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Heroic Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Intervene"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mortal Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shattering Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Skull Banner"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Staggering Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Taunt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Victory Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Fury"] = {
            ["Bloodthirst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Heroic Leap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Impending Victory"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mocking Banner"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Recklessness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Storm Bolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Sweeping Strikes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Thunder Clap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Protection_Warrior"] = {
            ["Avatar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Demoralizing Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Disarm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Enraged Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Last Stand"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mass Spell Reflection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Pummel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rallying Cry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Revenge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Safeguard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shield Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shield Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shield Slam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shield Wall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shockwave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spell Reflection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Vigilance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Druid Spells
    ------------------------
        ["Balance"] = {
            ["Barkskin"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Celestial Alignment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Heart of the Wild"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Incarnation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Incarnation: Chosen of Elune"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mass Entanglement"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Nature's Grasp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Nature's Swiftness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Remove Corruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Solar Beam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Starfall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Starsurge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Symbiosis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Typhoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ursol's Vortex"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wild Mushroom: Detonate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            },
        ["Feral_Combat"] = {
            ["Bear Hug"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Berserk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Disorienting Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Displacer Beast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Enrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Frenzied Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Growl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lacerate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Maim"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mangle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Maul"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Might of Ursoc"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mighty Bash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Prowl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Renewal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Savage Defense"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Skull Bash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stampeding Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Survival Instincts"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Swipe"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Thrash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Tiger's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wild Charge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            },
        ["Druid_Restoration"] = {
            ["Cenarion Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Force of Nature"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Incarnation: King of the Jungle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Innervate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ironbark"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Nature's Vigil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rebirth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Swiftmend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Tranquility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wild Growth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wild Mushroom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wild Mushroom: Bloom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            },
    ------------------------
    --Warlock spells
    ------------------------
      ["Affliction"] = {
            ["Blood Horror"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Create Soulwell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Soul: Knowledge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Soul: Misery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Howl of Terror"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mannoroth's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mortal Coil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Soulburn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Soulstone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Twilight Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
       ["Demonology"] = {
            ["Carrion Swarm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Soul"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Demonic Circle: Teleport"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Demonic Gateway"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Demonic Leap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Felhunter: Devour Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Felhunter: Spell Lock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Grimoire of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Grimoire of Service"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hand of Gul'dan"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Imp: Cauterize Master"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Imp: Flee"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Imp: Singe Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Metamorphosis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Metamorphosis: Chaos Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ritual of Summoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Sacrificial Pact"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Succubus: Whiplash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Summon Doomguard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Summon Infernal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Unending Resolve"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Voidwalker: Disarm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Voidwalker: Suffering"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Destruction"] = {
            ["Conflagrate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Bargain"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Soul: Instability"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Demonic Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fire and Brimstone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Flames of Xoroth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Havoc"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Seed of Corruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shadowfury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Soulshatter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Unbound Will"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Shaman spells
    ------------------------
        ["Elemental"] = {
            ["Ascendance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Call of the Elements"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Capacitor Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chain Lightning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Earth Elemental Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Earthgrab Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Earthquake"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Elemental Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Elemental Mastery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Grounding Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hex"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lava Burst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shamanistic Rage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stormlash Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Thunderstorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Totemic Projection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Tremor Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wind Shear"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Enhancement"] = {
            ["Astral Recall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Astral Shift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Earthbind Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Feral Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fire Elemental Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fire Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lava Lash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Primal Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spirit Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stone Bulwark Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stormblast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stormstrike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Unleash Elements"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Unleash Life"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Windwalk Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Shaman_Restoration"] = {
            ["Ancestral Guidance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ancestral Swiftness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Cleanse Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Healing Rain"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Healing Stream Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Healing Tide Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mana Tide Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Purify Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Riptide"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spirit Link Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spiritwalker's Grace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Shared_Shaman_spells"] = {
            Shocks = false,
        },
    ------------------------
    --Hunter spells
    ------------------------
        ["Beast Mastery"] = {
            ["A Murder of Crows"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Bestial Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Camouflage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dire Beast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Feed Pet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Intimidation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Kill Command"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lynx Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Master's Call"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Stampede"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
          },
        ["Marksmanship"] = {
            ["Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Binding Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chimera Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Concussive Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Counter Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Distracting Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Flare"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Kill Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Powershot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rapid Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Scatter Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Silencing Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Survival"] = {
            ["Deterrence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Disengage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Exhilaration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Explosive Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Feign Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fervor"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Glaive Toss"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Misdirection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Wyvern Sting"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Shared_Hunter_spells"] = {
            Traps = false,
        },
    ------------------------
    --Paladin
    ------------------------
        ["Holy_Paladin"] = {
            ["Cleanse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Divine Favor"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Divine Plea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Eternal Flame"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Holy Shock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lay on Hands"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Word of Glory"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Protection_Paladin"] = {
            ["Ardent Defender"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Avenger's Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Blinding Light"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Consecration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Devotion Aura"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Divine Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Divine Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fist of Justice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Guardian of Ancient Kings"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hammer of Justice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hammer of the Righteous"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hand of Freedom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hand of Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hand of Purity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hand of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hand of Salvation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Holy Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Reckoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Righteous Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Sacred Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Shield of the Righteous"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Turn Evil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Retribution"] = {
            ["Avenging Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Crusader Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Execution Sentence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Exorcism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Hammer of Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Holy Avenger"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Holy Prism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Judgment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Light's Hammer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rebuke"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Repentance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Speed of Light"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Mage
    ------------------------
        ["Arcane"] = {
            ["Alter Time"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ancient Portal: Dalaran"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Arcane Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Arcane Power"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Blink"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Conjure Refreshment Table"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Counterspell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Evocation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Greater Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Incanter's Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mirror Image"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Darnassus"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Exodar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Ironforge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Orgrimmar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Shattrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Silvermoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Stonard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Stormwind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Theramore"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Thunder Bluff"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Tol Barad"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Undercity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Portal: Vale of Eternal Blossoms"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Presence of Mind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Remove Curse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Temporal Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Time Warp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Fire"] = {
            ["Blazing Speed"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Combustion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dragon's Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fire Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Flamestrike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Inferno Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Frost_Mage"] = {
            ["Cold Snap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Cone of Cold"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Deep Freeze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Frost Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Frost Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Frostjaw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Frozen Orb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ice Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ice Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ice Floes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ice Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Icy Veins"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ring of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Summon Water Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Death_Knight
    ------------------------
        ["Blood"] = {
            ["Asphyxiate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Bone Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dancing Rune Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Command"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Death's Advance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Gorefiend's Grasp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Outbreak"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rune Tap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Soul Reaper"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Strangulate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Vampiric Blood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Frost_DK"] = {
            ["Empower Rune Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Horn of Winter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Icebound Fortitude"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Lichborne"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Mind Freeze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Pillar of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Remorseless Winter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Unholy"] = {
            ["Anti-Magic Shell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Anti-Magic Zone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Army of the Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dark Simulacrum"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Death Gate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Death Grip"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Death Pact"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Death and Decay"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Desecrated Ground"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Plague Leech"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Raise Ally"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Raise Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Summon Gargoyle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Unholy Blight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Unholy Frenzy"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Monk
    ------------------------
        ["Brewmaster"] = {
            ["Avert Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Clash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Dampen Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Diffuse Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Elusive Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fortifying Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Grapple Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Guard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Keg Smash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Nimble Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Provoke"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Summon Black Ox Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Tiger's Lust"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Touch of Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Zen Meditation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Mistweaver"] = {
            ["Chi Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chi Torpedo"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chi Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Detox"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Life Cocoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Renewing Mist"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Revival"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Ring of Peace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Summon Jade Serpent Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Thunder Focus Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Transcendence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Transcendence: Transfer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Zen Pilgrimage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Zen Sphere"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Windwalker"] = {
            ["Charging Ox Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Chi Burst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Energizing Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Expel Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Fists of Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Flying Serpent Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Invoke Xuen, the White Tiger"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Leer of the Ox"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Leg Sweep"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Paralysis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rising Sun Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Roll"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rushing Jade Wind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Spear Hand Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Tigereye Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Touch of Karma"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ------------------------
    --Racials
    ------------------------
        ["Draenei"] = {
            ["Gift of the Naaru"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Blood Elf"] = {
            ["Arcane Torrent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Undead"] = {
            ["Cannibalize"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Will of the Forsaken"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Orc"] = {
            ["Blood Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Troll"] = {
            ["Berserking"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Tauren"] = {
            ["War Stomp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Human"] = {
            ["Will to Survive"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Night Elf"] = {
            ["Shadowmeld"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Gnome"] = {
            ["Escape Artist"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Dwarf"] = {
            ["Stoneform"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Goblin"] = {
            ["Pack Hobgoblin"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rocket Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Rocket Jump"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Worgen"] = {
            ["Darkflight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
            ["Two Forms"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
        ["Pandaren"] = {
            ["Quaking Palm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        }
    }

local Lust_Table
if select(3, ASCT.API.Documentation["UnitClass"]("player")) == 7 and select(2, ASCT.API.Documentation["UnitFactionGroup"]("player")) == L["Alliance"] then
Lust_Table = {["Heroism"] = {SpellEnable = false, iconEnable = false, nameEnable = false}}
ASCT.Functions.Table["TableCombine"](ASCT.Database.Spells["Spells_MOP"]["Enhancement"], Lust_Table)
elseif select(3, ASCT.API.Documentation["UnitClass"]("player")) == 7 and select(2, ASCT.API.Documentation["UnitFactionGroup"]("player")) == L["Horde"] then
Lust_Table = { ["Bloodlust"] = {SpellEnable = false, iconEnable = false, nameEnable = false} }
ASCT.Functions.Table["TableCombine"](ASCT.Database.Spells["Spells_MOP"]["Enhancement"], Lust_Table)
end
end
