local ASCT = ASCT_Table
local Frame = ASCT.Strings.FrameName["Frame"]
ASCT.Frames.SARTE["Attack_Power_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Armor_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Experience_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Health_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Level_Up_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Resource_Loss_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Skill_Gained_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)
ASCT.Frames.SARTE["Skill_Up_Frame"] = ASCT.API.Documentation["CreateFrame"](Frame)