local ASCT = ASCT_Table
local Frames, Documentation, frameType = ASCT.Frames, ASCT.API.Documentation, ASCT.Strings.FrameType["Frame"]
Frames.SARTE["Attack_Power_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Armor_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Experience_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Health_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Level_Up_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Resource_Loss_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Skill_Gained_Frame"] = Documentation["CreateFrame"](frameType)
Frames.SARTE["Skill_Up_Frame"] = Documentation["CreateFrame"](frameType)