local isRetailWow = (WOW_PROJECT_ID == WOW_PROJECT_MAINLINE)

if isRetailWow then
SpellTableMonk = {--Monk Spells
--Brewmaster
["Paralysis"] = "Paralysis",
["Roll"] = "Roll",
["Leg Sweep"] = "Leg Sweep",
["Blackout Kick"] = "Blackout Kick",
["Touch of Death"] = "Touch of Death",
["Zen Meditation"] = "Zen Meditation",
["Purifying Brew"] = "Purifying Brew",
["Invoke Niuzao, the Black Ox"] = "Invoke Niuzao, the Black Ox",
["Keg Smash"] = "Keg Smash",
["Celestial Brew"] = "Celestial Brew",
["Breath of Fire"] = "Breath of Fire",
["Clash"] = "Clash",
["Summon Black Ox Statue"] = "Summon Black Ox Statue",
["Black Ox Brew"] = "Black Ox Brew",
["Exploding Keg"] = "Exploding Keg",
--Mistweaver
["Transcendence"] = "Transcendence",
["Transcendence: Transfer"] = "Transcendence: Transfer",
["Expel Harm"] = "Expel Harm",
["Detox"] = "Detox",
["Healing Elixir"] = "Healing Elixir",
["Life Cocoon"] = "Life Cocoon",
["Rising Sun Kick"] = "Rising Sun Kick",
["Essence Font"] = "Essence Font",
["Thunder Focus Tea"] = "Thunder Focus Tea",
["Revival"] = "Revival",
["Summon Jade Serpent Statue"] = "Summon Jade Serpent Statue",
["Invoke Chi-Ji, the Red Crane"] = "Invoke Chi-Ji, the Red Crane",
["Mana Tea"] = "Mana Tea",
["Refreshing Jade Wind"] = "Refreshing Jade Wind",
["Song of Chi-Ji"] = "Song of Chi-Ji",
--Windwalker
["Fortifying Brew"] = "Fortifying Brew",
["Zen Pilgrimage"] = "Zen Pilgrimage",
["Provoke"] = "Provoke",
["Touch of Fatality"] = "Touch of Fatality",
["Rushing Jade Wind"] = "Rushing Jade Wind",
["Diffuse Magic"] = "Diffuse Magic",
["Spear Hand Strike"] = "Spear Hand Strike",
["Storm, Earth, and Fire"] = "Storm, Earth, and Fire",
["Invoke Xuen, the White Tiger"] = "Invoke Xuen, the White Tiger",
["Fists of Fury"] = "Fists of Fury",
["Touch of Karma"] = "Touch of Karma",
["Flying Serpent Kick"] = "Flying Serpent Kick",
["Whirling Dragon Punch"] = "Whirling Dragon Punch",
["Fist of the White Tiger"] = "Fist of the White Tiger",
["Serenity"] = "Serenity",
["Energizing Elixir"] = "Energizing Elixir",
}
end