local ASCT, L = ASCT_Table, ASCT_locale_Table
if ASCT.Client.LE_EXPANSION_LEVEL["isDragonFlightWow"] and ASCT.Client.tocversion["is100107"] then
        ASCT.Database.Spells["Spells_DF"] = {
	--Races
	["Race"] = {
		["Blood Elf"] = false,
		["Orc"] = false,
		["Undead"] = false,
		["Troll"] = false,
		["Tauren"] = false,
		["Draenei"] = false,
		["Gnome"] = false,
		["Human"] = false,
		["Night Elf"] = false,
		["Dwarf"] = false,
		["Worgen"] = false,
		["Pandaren"] = false,
		["Void Elf"] = false,
		["Lightforged Draenei"] = false,
		["Dark Iron Dwarf"] = false,
		["Mechagnome"] = false,
		["Kul Tiran"] = false,
		["Goblin"] = false,
		["Nightborne"] = false,
		["Highmountain Tauren"] = false,
		["Vulpera"] = false,
		["Zandalari Troll"] = false,
		["Mag'har Orc"] = false,
		["Dracthyr"] = false,
		},
	--Classes
	["Class"] = {
		["Rogue"] = false,
		["Priest"] = false,
		["Warrior"] = false,
		["Druid"] = false,
		["Warlock"] = false,
		["Shaman"] = false,
      	        ["Hunter"] = false,
		["Paladin"] = false,
		["Mage"] = false,
		["Death_Knight"] = false,
		["Demon_Hunter"] = false,
		["Monk"] = false,
		["Evoker"] = false,
	},
	--Rogue spells
	["Assassination"] = {
		["Garrote"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Deathmark"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Exsanguinate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sepsis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Serrated Bone Spike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Indiscriminate Carnage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Kingsbane"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thistle Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cold Blood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Crimson Vial"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Kidney Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Smoke Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death from Above"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Outlaw"] = {
                ["Dismantle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Marked for Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Gouge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Feint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Evasion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shiv"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sprint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Between the Eyes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dreadblades"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Killing Spree"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blade Flurry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Adrenaline Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Grappling Hook"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blade Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ghostly Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Keep It Rolling"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Roll the Bones"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Subtlety"] = {
                ["Shadowy Duel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Echoing Reprimand"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadowstep"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tricks of the Trade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cloak of Shadows"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Vanish"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shroud of Concealment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Stealth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Distract"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadow Dance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadow Blades"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Symbols of Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Secret Technique"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Flagellation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shuriken Tornado"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
--Priest spells
	["Shadow"] = {
                ["Dominate Mind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Void Shift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mindgames"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadowfiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Vampiric Embrace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Void Tendrils"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Psychic Scream"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Void Bolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadow Word: Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mind Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mind Soothe"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dispersion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Void Torrent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dark Ascension"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mindbender"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadow Crash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Void Eruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Psychic Horror"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Silence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thoughtsteal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Inner Light and Shadow"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Psyfiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
        },
    ["Holy_Priest"] = {
		["Divine Star"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Halo"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Leap of Faith"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Desperate Prayer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Apotheosis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Lightwell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Word: Salvation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Word"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Word: Serenity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Symbol of Hope"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Hymn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Empyreal Blaze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Prayer of Mending"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Circle of Healing"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Word: Sanctify"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Word: Chastise"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Guardian Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ray of Hope"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Greater Heal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Ascension"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
    ["Discipline"] = {
		["Power Word: Life"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mass Dispel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Power Infusion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Penance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Purify"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Power Word: Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Angelic Feather"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Power Word: Radiance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Evangelism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Light's Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Power Word: Solace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadow Covenant"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rapture"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Power Word: Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Schism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Pain Suppression"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dark Archangel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Archangel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Luminous Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	  --Warrior spells
	["Arms"] = {
                ["Battle Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Charge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Colossus Smash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Die by the Sword"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Overpower"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Heroic Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Titanic Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shattering Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Berserker Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rallying Cry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wrecking Throw"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Impending Victory"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mortal Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Warbreaker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bladestorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Skullsplitter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cleave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sweeping Strikes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spear of Bastion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["War Banner"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sharpen Blade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Duel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Fury"] = {
                ["Execute"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Piercing Howl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Pummel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thunder Clap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Berserker Rage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Intervene"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bloodthirst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Onslaught"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Odyn's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Recklessness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Enraged Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Raging Blow"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thunderous Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Avatar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Intimidating Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bitter Immunity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death Wish"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bloodrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Protection_Warrior"] = {
                ["Shield Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Heroic Leap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shield Slam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Taunt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spell Reflection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Last Stand"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ravager"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shield Charge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spell Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shield Wall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Disrupting Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Challenging Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Demoralizing Shout"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shockwave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Storm Bolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Disarm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Oppressor"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shield Bash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bodyguard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dragon Charge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
        --Warlock spells
	["Affliction"] = {
                ["Ritual of Summoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Create Soulwell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soulstone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dark Pact"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Amplify Curse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mortal Coil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soul Swap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Howl of Terror"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soul Rot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Darkglare"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Vile Taint"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Haunt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Grimoire of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Phantom Singularity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Nether Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadow Rift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Call Observer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Oblivion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
    ["Demonology"] = {
                ["Soulburn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fel Domination"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Inquisitor's Gaze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Demonic Gateway"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Vilefiend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Guillotine"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Nether Portal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Demonic Tyrant"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Grimoire: Felguard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Power Siphon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Demonic Strength"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bilescourge Bombers"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soul Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Call Dreadstalkers"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fel Obelisk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Call Fel Lord"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Call Felhunter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Destruction"] = {
                ["Ritual of Doom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Unending Resolve"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadowflame"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Conflagrate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dimensional Rift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cataclysm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Infernal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadowburn"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soul Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Channel Demonfire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Havoc"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shadowfury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bane of Havoc"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rapid Contagion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bonds of Fel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
		--Druid Spells
	["Balance"] = {
                ["Barkskin"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dreamwalk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Charm Woodland Creature"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mass Entanglement"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Heart of the Wild"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ursol's Vortex"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Typhoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fury of Elune"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["New Moon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Convoke the Spirits"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Solar Beam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Force of Nature"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Celestial Alignment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wild Mushroom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Astral Communion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Warrior of Elune"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Faerie Swarm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Feral_Combat"] = {
                ["Dash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thrash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mangle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Prowl"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Incapacitating Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soothe"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mighty Bash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Skull Bash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tiger Dash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Maim"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Frenzied Regeneration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Berserk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Feral Frenzy"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Incarnation: Avatar of Ashamane"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Survival Instincts"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Brutal Slash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tiger's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bristling Fur"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rage of the Sleeper"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Pulverize"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Alpha Challenge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Demoralizing Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Overrun"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Emerald Slumber"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Grove Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Lunar Beam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Druid_Restoration"] = {
		["Nature's Swiftness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rebirth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Nature's Vigil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Renewal"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Innervate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Swiftmend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Remove Corruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Nature's Cure"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Flourish"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Adaptive Swarm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ironbark"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tranquility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cenarion Ward"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Invigorate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Overgrowth"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Incarnation: Tree of Life"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thorns"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Shaman spells
	["Elemental"] = {
                ["Hex"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Flame Shock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Lava Burst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ancestral Guidance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Lightning Lasso"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thunderstorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Stormkeeper"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Liquid Magma Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fire Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Storm Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Primordial Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Elemental Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Icefury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Gust of Wind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wind Shear"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Unleash Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Enhancement"] = {
                ["Astral Shift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Earthbind Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Earth Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Stoneskin Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tranquil Air Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spirit Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Earthgrab Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fire Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Feral Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Crash Lightning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sundering"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Doom Winds"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ice Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Feral Lunge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Stormstrike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Lava Lash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Astral Recall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wind Rush Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Greater Purge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tremor Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Capacitor Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Skyfury Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Grounding Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Counterstrike Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Static Field Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Shaman_Restoration"] = {
		["Nature's Swiftness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ascendance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ancestral Protection Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cloudburst Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Downpour"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Healing Tide Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Healing Rain"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Healing Stream Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Poison Cleansing Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Totemic Recall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spiritwalker's Grace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mana Tide Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cleanse Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Purify Spirit"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Riptide"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Unleash Life"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spirit Link Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wellspring"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Earthen Wall Totem"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Hunter spells
	["Beast Mastery"] = {
                ["Mend Pet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Exhilaration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Feed Pet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wake Up"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Stampede"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Intimidation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Misdirection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["A Murder of Crows"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aspect of the Wild"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bestial Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dire Beast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bloodshed"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Barbed Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dire Beast: Basilisk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Roar of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dire Beast: Hawk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wild Kingdom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
    ["Marksmanship"] = {
                ["Flare"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death Chakram"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Disengage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wailing Arrow"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Scatter Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Explosive Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tranquilizing Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Survival of the Fittest"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Concussive Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Kill Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rapid Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Trueshot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Volley"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bursting Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aimed Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sniper Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chimaeral Sting"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
    ["Survival"] = {
                ["Freezing Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Feign Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["High Explosive Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Steel Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Camouflage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Binding Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Kill Command"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Counter Shot"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tar Trap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Carve"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Butchery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spearhead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fury of the Eagle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Coordinated Assault"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Flanking Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wildfire Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aspect of the Eagle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Harpoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aspect of the Turtle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aspect of the Cheetah"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aspect of the Chameleon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mending Bandage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tracker's Net"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Interlope"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
    },
	--Paladin
	["Holy_Paladin"] = {
                ["Hand of Reckoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Consecration"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Intercession"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cleanse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rebuke"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Turn Evil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Lay on Hands"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of Freedom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Avenging Crusader"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Light's Hammer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Beacon of Virtue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Prism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of Summer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Barrier of Faith"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tyr's Deliverance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Favor"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rule of Law"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Aura Mastery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Holy Shock"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shield of Virtue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Hand of Divinity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Daybreak"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Protection_Paladin"] = {
                ["Hammer of Justice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blinding Light"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of Protection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of Sacrifice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Steed"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Hammer of Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sentinel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of Spellwarding"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Moment of Glory"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Toll"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Eye of Tyr"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Guardian of Ancient Kings"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bastion of Light"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Hammer of the Righteous"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ardent Defender"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessed Hammer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Avenger's Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Inquisition"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Guardian of the Forgotten Queen"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Retribution"] = {
                ["Contemplation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Avenging Wrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Judgment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Repentance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Crusade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Justicar's Vengeance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Eye for an Eye"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Radiant Decree"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Final Reckoning"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Execution Sentence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Hand of Hindrance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Exorcism"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shield of Vengeance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Divine Hammer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wake of Ashes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blade of Justice"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of Sanctuary"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Mage Spells
	["Arcane"] = {
                        --Portals
                ["Portal: Shattrath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Stonard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Theramore"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Silvermoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Exodar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Stormwind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Ironforge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Darnassus"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Orgrimmar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Undercity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Thunder Bluff"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Oribos"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Dalaran - Northrend"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ancient Portal: Dalaran"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Warspear"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Vale of Eternal Blossoms"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Tol Barad"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Portal: Valdrakken"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                --End
                ["Time Warp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blink"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Illusion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Counterspell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Conjure Refreshment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shimmer"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Displacement"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mass Polymorph"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Greater Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Alter Time"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mirror Image"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Remove Curse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Prismatic Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Arcane Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Radiant Spark"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Evocation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Supernova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Touch of the Magi"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Presence of Mind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Arcane Surge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Arcane Orb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Arcane Familiar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Temporal Shield"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mass Invisibility"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Arcanosphere"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mass Barrier"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Fire"] = {
                ["Fire Blast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dragon's Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blast Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Alexstrasza's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Living Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Combustion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Phoenix Flames"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Greater Pyroblast"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ring of Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Frost_Mage"] = {
                ["Cone of Cold"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shifting Power"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Frost Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ice Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ice Block"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ring of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ice Floes"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Water Elemental"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ebonbolt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ray of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Comet Storm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Icy Veins"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cold Snap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Flurry"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blizzard"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Frozen Orb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Snowdrift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ice Form"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Frost Bomb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ice Wall"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Demon Hunter Spells
	["Havoc"] = {
                ["Fel Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Immolation Aura"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Metamorphosis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spectral Sight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["The Hunt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Consume Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Imprison"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sigil of Flame"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Glaive Tempest"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Essence Break"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fel Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Elysian Decree"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Netherwalk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fel Eruption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Eye Beam"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rain from Above"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Reverse Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Vengeance"] = {
                ["Darkness"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Torment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Throw Glaive"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Felblade"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sigil of Misery"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chaos Nova"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Disrupt"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Vengeful Retreat"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bulk Extraction"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sigil of Silence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fracture"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soul Carver"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sigil of Chains"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fel Devastation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fiery Brand"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tormentor"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Demonic Trample"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Illidan's Grasp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Death_Knight Spells
	["Blood"] = {
                ["Dark Command"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Corpse Exploder"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death Grip"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sacrificial Pact"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mark of Blood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tombstone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blooddrinker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Consumption"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Gorefiend's Grasp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Bonestorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blood Tap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Vampiric Blood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dancing Rune Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blood Boil"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rune Tap"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death's Caress"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Murderous Intent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dark Simulacrum"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Frost_DK"] = {
                ["Lichborne"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Soul Reaper"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Empower Rune Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wraith Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Icebound Fortitude"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blinding Sleet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Anti-Magic Zone"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mind Freeze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Remorseless Winter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Breath of Sindragosa"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Frostwyrm's Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chill Streak"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Horn of Winter"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Pillar of Frost"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Strangulate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Unholy"] = {
                ["Death's Advance"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death Gate"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Raise Ally"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death and Decay"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Raise Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Abomination Limb"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Anti-Magic Shell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Defile"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Unholy Assault"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Gargoyle"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Army of the Dead"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Vile Contagion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dark Transformation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Apocalypse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Unholy Blight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Death Chain"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Monk Spells
	["Brewmaster"] = {
                ["Touch of Death"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Touch of Fatality"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blackout Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chi Torpedo"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Black Ox Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon White Tiger Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chi Burst"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rising Sun Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Black Ox Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rushing Jade Wind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Weapons of Order"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Exploding Keg"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Invoke Niuzao, the Black Ox"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Breath of Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Clash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Zen Meditation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Celestial Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Keg Smash"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Purifying Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Admonishment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mighty Ox Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Grapple Weapon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Nimble Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Mistweaver"] = {
                ["Zen Pilgrimage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Summon Jade Serpent Statue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Expel Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chi Wave"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Transcendence"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Detox"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tiger's Lust"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Healing Elixir"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Mana Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Faeline Stomp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Refreshing Jade Wind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Invoke Yu'lon, the Jade Serpent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Invoke Chi-Ji, the Red Crane"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Restoral"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Zen Pulse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Revival"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Essence Font"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Thunder Focus Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Life Cocoon"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Renewing Mist"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Healing Sphere"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Zen Focus Tea"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Windwalker"] = {
                ["Provoke"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Leg Sweep"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dampen Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spear Hand Strike"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Paralysis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Ring of Peace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fortifying Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Diffuse Magic"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Storm, Earth, and Fire"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Serenity"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Whirling Dragon Punch"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Invoke Xuen, the White Tiger"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Strike of the Windlord"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fists of Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Flying Serpent Kick"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Touch of Karma"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Avert Harm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Double Barrel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tigereye Brew"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Evoker Spells
	["Devastation"] = {
                ["Fire Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Hover"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Deep Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Landslide"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Zephyr"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Oppressing Roar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rescue"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Unravel"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Sleep Walk"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cauterizing Flame"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Quell"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Obsidian Scales"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Eternity Surge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Firestorm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Shattering Star"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dragonrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Nullifying Shroud"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Time Stop"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Preservation"] = {
                ["Emerald Blossom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Blessing of the Bronze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Fury of the Aspects"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Naturalize"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Time Spiral"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Renewing Blaze"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tip the Scales"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Verdant Embrace"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Expunge"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dream Breath"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dream Flight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Stasis"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Temporal Anomaly"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Emerald Communion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Time Dilation"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Spiritbloom"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rewind"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Reversion"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Chrono Loop"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Swoop Up"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Dream Projection"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	--Racials
	["Blood Elf"] = {
		["Arcane Torrent"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Dracthyr"] = {
		["Soar"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Tail Swipe"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Wing Buffet"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Dark Iron Dwarf"] = {
		["Fireblood"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
		["Mole Machine"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Draenei"] = {
		["Gift of the Naaru"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Goblin"] = {
		["Pack Hobgoblin"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rocket Barrage"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rocket Jump"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Dwarf"] = {
		["Stoneform"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Highmountain Tauren"] = {
		["Bull Rush"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Gnome"] = {
		["Escape Artist"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Mag'har Orc"] = {
		["Ancestral Call"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Human"] = {
		["Will to Survive"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Nightborne"] = {
		["Arcane Pulse"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cantrips"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Kul Tiran"] = {
		["Haymaker"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Orc"] = {
		["Blood Fury"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Lightforged Draenei"] = {
		["Forge of Light"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Light's Judgment"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Pandaren"] = {
		["Quaking Palm"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Mechagnome"] = {
		["Hyper Organic Light Originator"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Tauren"] = {
		["War Stomp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Night Elf"] = {
		["Shadowmeld"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Troll"] = {
		["Berserking"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Void Elf"] = {
		["Spatial Rift"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Undead"] = {
		["Will of the Forsaken"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Cannibalize"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Vulpera"] = {
		["Bag of Tricks"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Make Camp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Return to Camp"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Rummage Your Bag"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Worgen"] = {
		["Darkflight"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
	["Zandalari Troll"] = {
		["Embrace of the Loa"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Pterrordax Swoop"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
                ["Regeneratin'"] = {SpellEnable = false, iconEnable = false, nameEnable = false},
	},
}
local Lust_Table
if select(3, ASCT.API.Documentation["UnitClass"]("player")) == 7 and select(2, ASCT.API.Documentation["UnitFactionGroup"]("player")) == L["Alliance"] then
Lust_Table = {["Heroism"] = {SpellEnable = false, iconEnable = false, nameEnable = false}}
ASCT.Functions.Table["TableCombine"](ASCT.Database.Spells["Spells_DF"]["Enhancement"], Lust_Table)
elseif select(3, ASCT.API.Documentation["UnitClass"]("player")) == 7 and select(2, ASCT.API.Documentation["UnitFactionGroup"]("player")) == L["Horde"] then
Lust_Table = { ["Bloodlust"] = {SpellEnable = false, iconEnable = false, nameEnable = false} }
ASCT.Functions.Table["TableCombine"](ASCT.Database.Spells["Spells_DF"]["Enhancement"], Lust_Table)
end
end